### ISSUE TITLE
shift-babel-converter

### ISSUE THREAD

**Issue by gabejohnson** [shapesecurity/shift-spidermonkey-converter-js#16]
I created a fork https://github.com/gabejohnson/shift-spidermonkey-converter-js/tree/babel to address https://github.com/mozilla/sweet.js/issues/515.

I'm opening this issue to discuss how to handle it going forward. @disnet rightly thinks it would be best for Sweet to depend on a published lib vs my github repo.

The question is, does Shape want to take on the fork as a separate project? Or should I publish this myself?

**Comment by gabejohnson** [comment]
@michaelficarra: On second thought, I think making the converters class-based might make more sense. Then Shape can host the ESTree converters and I can just extend them. Thoughts?

**Comment by michaelficarra** [comment]
Now that #17 is in, this is unblocked.
