### ISSUE TITLE
Update to current shift specs

### ISSUE THREAD

**Issue by gabejohnson** [shapesecurity/shift-spidermonkey-converter-js#9]
I've been doing a little work to update ```toShift``` and ```toSpidermonkey``` but before I get much further I'd like an idea of where this project is headed (if anywhere).

I started the update targeting Esprima but I could see targeting Babel or Acorn, maybe all of them.

I'd appreciate any feedback.

**Comment by michaelficarra** [comment]
Thank you for your interest, @gabejohnson. This is the last of the first-party Shift tools that we've not updated with ES2015 support. We were planning on updating it in the next few weeks, skipping straight to ES2016 support. We had also planned to continue converting to/from the estree (formerly SpiderMonkey) format. I'm aware of at least one person (@disnet) that would like a Shift/Babel converter. Hope that helps.

**Comment by gabejohnson** [comment]
https://github.com/mozilla/sweet.js/issues/515 is actually the issue that got me interested.

So far I've updated Esprima for the tests and to Babel for build. 52 of 57 test are passing. If you're planning on going with the same design for the converter I already have a lot of the code modified. Otherwise I can just wait on your work and extend the converter for Babel.

**Comment by gabejohnson** [comment]
Though I suppose if you're planning on jumping straight to es2016, I would have to wait for the updates to shift-ast anyway.

**Comment by gabejohnson** [comment]
Progress so far:
https://github.com/gabejohnson/shift-spidermonkey-converter-js/tree/es6-update

**Comment by michaelficarra** [comment]
FYI, you can see the changes between the ES2015 format and the ES2016 format in [this diff](https://github.com/shapesecurity/shift-spec/compare/es6...es2016). Aside from https://github.com/shapesecurity/shift-spec/pull/105, this list of changes should be final.

**Comment by gabejohnson** [comment]
Thanks @michaelficarra I have most of the update complete. Just having a little trouble with `Shift.StaticPropertyName`. I can't seem to find a clear way to determine if the node represents a property identifier or a string literal.

example:

```
class A extends B {
  constructor() {
    super()
  }
}
```

Here `constructor` is a `Shift.StaticPropertyName` with `node.value === "constructor"`. In esprima it's a `Node.Identifier` with `node.name === "constructor"`.

However if I change this to:

```
class A extends B {
  "constructor"() {
    super()
  }
}
```

Now `"constructor"` is still a `Shift.StaticPropertyName` with `node.value === "constructor"` but `Node.Literal` with `node.value === "constructor"`.

**Comment by bakkot** [comment]
@gabejohnson, Shift doesn't distinguish between the two, since there's no semantic difference. The simplest solution is probably to translate all Shift StaticPropertyNames to Esprima Literal nodes.

**Comment by gabejohnson** [comment]
@bakkot, that's what I ended up doing. I'm just cleaning up now and will submit a PR tonight with my progress.
